import { z } from 'zod';

/** Current version of the generated `assets/manifest.json` format. */
export const ASSET_MANIFEST_VERSION = 1;

const fileName = z.string().regex(/^[a-z0-9_-]+\.(png|json)$/, 'must be a bare file name');

/**
 * Schema for `assets/manifest.json`, generated by `tools/build-atlas.ts`.
 * It links content sprite keys to atlas frames so the game never hard-codes frame names.
 */
export const assetManifestSchema = z.strictObject({
  version: z.literal(ASSET_MANIFEST_VERSION),
  atlases: z
    .array(
      z.strictObject({
        key: z.string().min(1),
        /** File names relative to `assets/atlas/`. */
        image: fileName,
        data: fileName,
      }),
    )
    .min(1),
  sprites: z.record(
    z.string(),
    z.strictObject({
      atlas: z.string().min(1),
      /** True while the sprite is a generated greybox; M7 requires zero placeholders. */
      placeholder: z.boolean(),
      /** Clip name → ordered atlas frame names. */
      clips: z.record(z.string(), z.array(z.string().min(1)).min(1)),
    }),
  ),
});

export type AssetManifest = z.infer<typeof assetManifestSchema>;
